#!/usr/bin/awk -f
# Convert specially formatted Forth program into Markdown
BEGIN { lines = 1; state = 0 }
/^bye/ { ended = 1; }
(!/^\\/ && !/^[ \t]*$/) && !ended { if(!state) { print "\n" } printf "\t%04u %s\n", lines++, $0; state = 1; }
( /^\\/ || /^[ \t]$/) && !ended { if(state) { print "\n" } gsub(/^\\ ?/, ""); gsub(/_/, "\\_"); print $0; state = 0; }
ended { if(!/^\t/) {gsub(/_/, "\\_") } print $0 }

